// Programming Project

/*
 * Defining error codes and values
 */

#define EXIT_NO_ARGS 0
#define EXIT_NO_ERRORS 0
#define EXIT_WRONG_ARG_COUNT 1
#define EXIT_BAD_INPUT_FILE 2
#define EXIT_BAD_MAGIC_NUMBER 3
#define EXIT_BAD_COMMENT_LINE 4
#define EXIT_BAD_DIMENSIONS 5
#define EXIT_BAD_GRAY 6
#define EXIT_BAD_MALLOC 7
#define EXIT_BAD_DATA 8
#define EXIT_OUTPUT_FAILED 9
#define EXIT_BAD_LAYOUT 10
#define EXIT_MISC 100

#define MAGIC_NUMBER_RAW_PGM 0x3550
#define MAGIC_NUMBER_ASCII_PGM 0x3250
#define MIN_IMAGE_DIMENSION 1
#define MAX_IMAGE_DIMENSION 65535
#define MAX_COMMENT_LINE_LENGTH 128

#define READ_SUCCESS 0
#define MAX_COMMENT_LINE_LENGTH 128

#define MAX_GREY_VALUE 255
#define MIN_GREY_VALUE 0
#define WIDTH 0
#define HEIGHT 0


